### ISSUE TITLE
 Incorrect method "user.authenticate"

### ISSUE THREAD

**Issue by Damon-sh** [kmpm/zabbix-dynamic-pdf-report#1]
Hi,
Did any configure on zabbix server?
I found  error blow when use this product.My ZABBIX SERVER's version is 3.0 and I have try on php version 5.5 and 7.0.
Unable to login: Array ( [code] => -32602 [message] => Invalid params. [data] => Incorrect method "user.authenticate". )

**Comment by kmpm** [comment]
Did not do anything special on my zabbix server.
Using version Zabbix 3.0.5, and I think it's PHP7 but not 100% sure.

**Comment by scm** [comment]
I also got this problem so after checking the user group permissions I checked the api docs for Zabbix 3.

I needed to change **user.authenticate** to **user.login** in the following files: 
**inc/ZabbixAPI.class.php.org**
**inc/ZabbixAPI.class.php**

Resolved my issue, thanks for this neat tool.

**Comment by idanbenyair** [comment]
Hi guys, I am a bit lost. Can someone help me? The owner of this repo doesn't seem to be assisting. Does this work for Zabbix 3? I tried setting this up but wasn't able to get anywhere with it. Also, once its setup. How do I send these reports to email?
