### ISSUE TITLE
Issue in date selection in Custom Report

### ISSUE THREAD

**Issue by saumyajit** [kmpm/zabbix-dynamic-pdf-report#2]
Hi,

I've configured 'zabbix-dynamic-pdf-report' & it's giving proper details while generating report for fixed timing. But while trying to generate Custom report, when i select date, it's displaying. But nest moment when i'm going to next tab (i.e. time) for selecting time, the date entry is getting vanished. 

Kindly suggest.

Regards,
Saumyajit
![issue](https://user-images.githubusercontent.com/18307963/27503061-b01cedcc-5896-11e7-9b7c-6bd4225126e5.PNG)

**Comment by anps14** [comment]
Hello do you solve the issue? I have the same problem
